package main

import (
	_ "github.com/aliakbariaa1996/ethereum/cmd/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/aliakbariaa1996/ethereum/config"
	"github.com/aliakbariaa1996/ethereum/server"
	"github.com/joho/godotenv"
	"github.com/sirupsen/logrus"
	"log"
)

// @title Swagger Ether API
// @version 1.0
// @description This is a Ether Server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2

func main() {
	logrus.SetFormatter(new(logrus.JSONFormatter))
	cfg, err := config.InitConfig()
	if err != nil {
		logrus.Fatalf("errorx initializing configs: %s", err.Error())
	}

	if err := godotenv.Load("./../.env"); err != nil {
		logrus.Fatalf("errorx loading env variables: %s", err.Error())
	}

	// database connection ...
	ioWriter := log.Writer()
	logger := log.New(ioWriter, "ether", 1)

	app, err := server.NewServer(cfg, logger)

	if err := app.RunServer(cfg.Port); err != nil {
		log.Fatalf("%s", err.Error())
	}
}
